arch_dir=$(kernel_dir)/arch
boot_dir=$(kernel_dir)/boot
ds_dir=$(kernel_dir)/ds
dev_dir=$(kernel_dir)/dev
firmware_dir=$(kernel_dir)/firmware
fs_dir=$(kernel_dir)/fs
lime_dir=$(kernel_dir)/lime
lib_dir=$(kernel_dir)/lib
mm_dir=$(kernel_dir)/mm
modules_dir=$(kernel_dir)/modules
sync_dir=$(kernel_dir)/sync
sys_dir=$(kernel_dir)/sys

include $(arch_dir)/makefile
include $(boot_dir)/makefile
include $(ds_dir)/makefile
include $(dev_dir)/makefile
include $(firmware_dir)/makefile
include $(fs_dir)/makefile
include $(lime_dir)/makefile
include $(lib_dir)/makefile
include $(mm_dir)/makefile
include $(modules_dir)/makefile
include $(sync_dir)/makefile
include $(sys_dir)/makefile


kernel_objs:=\
$(boot_objs)\
$(arch_objs)\
$(ds_objs)\
$(dev_objs)\
$(firmware_objs)\
$(fs_objs)\
$(lime_objs)\
$(lib_objs)\
$(mm_objs)\
$(modules_objs)\
$(sync_objs)\
$(sys_objs)\
$(kernel_dir)/kernel.o