
x86_64_objs+=\
$(x86_64_dir)/cpu.o\
$(x86_64_dir)/gdt.o\
$(x86_64_dir)/init.o\
$(x86_64_dir)/ipi.o\
$(x86_64_dir)/isrs.o\
$(x86_64_dir)/lapic.o\
$(x86_64_dir)/paging.o\
$(x86_64_dir)/regs.o\
$(x86_64_dir)/sse.o\
$(x86_64_dir)/signal.o\
$(x86_64_dir)/swtch.o\
$(x86_64_dir)/thread.o\
$(x86_64_dir)/trampoline.o\
$(x86_64_dir)/traps.o